name: PR_Title_Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check_title_of_pr:
    uses: kmieciak-m/WebAssemblyBrowserApp1/.github/workflows/pr_title_check.yml@master
